// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/yourapp_api/yourapp_api.proto

package yourapp_api

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/gogo/protobuf/gogoproto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/mwitkow/go-proto-validators"
	time "time"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

func (this *SignInRequest) Validate() error {
	if this.Email == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Email", fmt.Errorf(`value '%v' must not be an empty string`, this.Email))
	}
	if this.Password == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Password", fmt.Errorf(`value '%v' must not be an empty string`, this.Password))
	}
	return nil
}
func (this *SignInResponse) Validate() error {
	return nil
}
func (this *SignUpRequest) Validate() error {
	if this.Email == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Email", fmt.Errorf(`value '%v' must not be an empty string`, this.Email))
	}
	if this.Password == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Password", fmt.Errorf(`value '%v' must not be an empty string`, this.Password))
	}
	return nil
}
func (this *SignUpResponse) Validate() error {
	return nil
}
func (this *ProfileRequest) Validate() error {
	return nil
}
func (this *ProfileResponse) Validate() error {
	if this.LastLoginAt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.LastLoginAt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("LastLoginAt", err)
		}
	}
	return nil
}
